git:
  submodules: false
language: python
install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-add-repository -y ppa:aims/sagemath
  - sudo apt-get update -qq
  - sudo apt-get install sagemath-upstream-binary
script: sage test/test.py